#!/bin/bash
# -----------------------------------------------------------------------------
# Checks whether the specified ONOS cluster node has the desired state.
# -----------------------------------------------------------------------------

aux=/tmp/stc/stc-$$.log
trap "rm -f $aux 2>/dev/null" EXIT

onos "onos:nodes" > $aux
cat $aux

# Normalize the node status
state=$(grep ${1} $aux | cut -d, -f3 | cut -d= -f2)

[ "$state" = "${2:-READY}" ] && exit 0
sleep 1

exit 1